### ISSUE TITLE
Full World DB

### ISSUE THREAD

**Issue by kuramajssken001** [shenna-elysium/pvpserver#1]
world full database where donwload?
@shenna-elysium

**Comment by shenna-elysium** [comment]
This is a `fun server` edition for PvP-guild playing premades, with tier vendors, teleporting NPCs, instant 60 and stuff like this, why'd you need a full world DB of it?

**Comment by kuramajssken001** [comment]
@shenna-elysium Yeah, I need world DB.  thank you shenna-elysium.
